CREATE ROLE blynk LOGIN ENCRYPTED PASSWORD ':psw' NOINHERIT VALID UNTIL 'infinity';
CREATE DATABASE blynk WITH ENCODING='UTF8' OWNER=blynk;
CREATE DATABASE blynk_reporting WITH ENCODING='UTF8' OWNER=blynk;
